services:

  tos-trip-api:
    build:
      context: .

    image: tos-trip-api
    container_name: tos-trip-api

    ports:
      - "3002:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_URL: jdbc:postgresql://tos-trip-db:5432/postgres
      DB_USERNAME: test
      DB_PASSWORD: 1234

      FILE_UPLOAD_PATH: /upload/
      FILE_BASE_URI: https://derleng-api.eunglyzhia.social/images/

    volumes:
      - ./upload:/upload

    depends_on:
      - tos-trip-db

    networks:
      - tos-trip-net


  tos-trip-db:
    image: postgres:17

    container_name: tos-trip-db

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234

    volumes:
      - tostrip-pg-vol:/var/lib/postgresql/data

    networks:
      - tos-trip-net


volumes:
  tostrip-pg-vol:


networks:
  tos-trip-net: