services:
  tos-trip-api:
    image: "tos-trip-api"
    build:
      context: .
    container_name: tos-trip-api
    ports:
      - "3002:8080" # Map the application port
    environment:
        - SPRING_PROFILES_ACTIVE=docker
    networks:
      - tos-trip-net
    volumes:
      - "./upload:/upload" # bind mount
  tos-trip-db:
    image: postgres:latest
    container_name: tos-trip-db
    ports:
      - "3001:5432" # Map the application port
    environment:
      - POSTGRES_DB=tos_der_leng
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=tos_der
    volumes:
      - tostrip-pg-vol:/var/lib/postgresql/data
    networks:
        - tos-trip-net
volumes:
  tostrip-pg-vol:
networks:
  tos-trip-net:


