spring:
  datasource:
    url: jdbc:postgresql://136.228.158.126:3001/tos_der_leng
  config:
    activate:
      on-profile: docker

file-upload:
  server-path: /upload/
  base-uri: https://tos-der.sokpheng.com/images/